/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.banksystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class checkbalance extends javax.swing.JFrame {

    /**
     * Creates new form checkbalance
     */
    public checkbalance() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        checkbalanceaccount = new javax.swing.JLabel();
        accountno = new javax.swing.JTextField();
        checkbalancepassword = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        checkbalancesubmit = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        password = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        checkbalanceaccount.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        checkbalanceaccount.setText("Account No");
        checkbalanceaccount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(checkbalanceaccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 314, 136, 33));
        getContentPane().add(accountno, new org.netbeans.lib.awtextra.AbsoluteConstraints(757, 314, 143, 33));

        checkbalancepassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        checkbalancepassword.setText("Password");
        checkbalancepassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(checkbalancepassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 428, 136, 33));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Check Balance");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(506, 169, -1, -1));

        checkbalancesubmit.setBackground(new java.awt.Color(51, 102, 255));
        checkbalancesubmit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        checkbalancesubmit.setForeground(new java.awt.Color(255, 255, 255));
        checkbalancesubmit.setText("Submit");
        checkbalancesubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkbalancesubmitActionPerformed(evt);
            }
        });
        getContentPane().add(checkbalancesubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(616, 563, -1, -1));

        jButton1.setBackground(new java.awt.Color(51, 102, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 102, 51));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 340, 70));
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(757, 428, 143, 32));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        transaction t1=new transaction();
        t1.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void checkbalancesubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkbalancesubmitActionPerformed
    try{
        Connection con=null;
        try{
               Class.forName("com.mysql.jdbc.Driver");
              con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Banksystem","root","");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(checkbalance.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(checkbalance.class.getName()).log(Level.SEVERE, null, ex);
        }
        PreparedStatement ps=con.prepareStatement("Select * from transcation where account=? and password=? order by transactionid desc");
        ps.setString(1,accountno.getText());
        ps.setString(2, password.getText());
        ResultSet rs=ps.executeQuery();
       if(rs.next()){
       String amount=rs.getString("balance");
       //showcheckbalance.setText("Your Accouunt Balance is "+amount);
        JOptionPane.showMessageDialog(null, "Account Balance is "+amount);
        transaction t78=new transaction();
        t78.setVisible(true);
           setVisible(false);
        
    }
       else{
               JOptionPane.showMessageDialog(null, "Please Enter Valid Required Feilds");
               }
       
       con.close();
               } 
   
        catch (SQLException ex) {
            Logger.getLogger(checkbalance.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    
    }//GEN-LAST:event_checkbalancesubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(checkbalance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(checkbalance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(checkbalance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(checkbalance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new checkbalance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accountno;
    private javax.swing.JLabel checkbalanceaccount;
    private javax.swing.JLabel checkbalancepassword;
    private javax.swing.JButton checkbalancesubmit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField password;
    // End of variables declaration//GEN-END:variables
}
