/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.banksystem;

import com.toedter.calendar.JDateChooser;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author DELL
 */
public class costumerregister extends javax.swing.JFrame {

    /**
     * Creates new form costumerregister
     */
    String formattedaccno="";
    public costumerregister() {
        initComponents();
             try{
        Connection con=null;
                 con= DriverManager.getConnection("jdbc:mysql://localhost:3306/Banksystem","root","");
     
        String  ac_no_prefix="10010001";
        int accountno=1;
        PreparedStatement ps_get = con.prepareStatement("select max(cast(accountno as int)) as accountno from customer");
        ResultSet rs_get=ps_get.executeQuery();
        if(rs_get.next())
        {
          accountno=rs_get.getInt("accountno")+1;
        }
        else
        {
            accountno=1;
        }
        formattedaccno=String.format("%03d", accountno);
       account.setText(ac_no_prefix+""+formattedaccno);
       account.setEditable(false);
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        weastflkh = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        sdlkfdh = new javax.swing.JLabel();
        dpbe = new javax.swing.JLabel();
        dggj = new javax.swing.JLabel();
        yutyui = new javax.swing.JLabel();
        dgfdh = new javax.swing.JLabel();
        rthf = new javax.swing.JLabel();
        eet = new javax.swing.JLabel();
        lname = new javax.swing.JTextField();
        contect = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        aadhar = new javax.swing.JTextField();
        account = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        register = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        initialamount = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        dob = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Customer Register");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, -1, -1));

        weastflkh.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        weastflkh.setText("First Name");
        weastflkh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(weastflkh, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 119, 136, 32));

        fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameActionPerformed(evt);
            }
        });
        getContentPane().add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(789, 119, 136, 32));

        sdlkfdh.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        sdlkfdh.setText("Last Name");
        sdlkfdh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(sdlkfdh, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 181, 136, 32));

        dpbe.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        dpbe.setText("DOB");
        dpbe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(dpbe, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 243, 136, 32));

        dggj.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        dggj.setText("Contect No.");
        dggj.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(dggj, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 305, 136, 32));

        yutyui.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        yutyui.setText("Email Id");
        yutyui.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(yutyui, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 367, 136, 32));

        dgfdh.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        dgfdh.setText("Aadhar No");
        dgfdh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(dgfdh, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 429, 136, 32));

        rthf.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rthf.setText("Account No");
        rthf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(rthf, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 491, 136, 32));

        eet.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        eet.setText("Initial Amount");
        eet.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(eet, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 550, 136, 32));
        getContentPane().add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(789, 181, 136, 32));

        contect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                contectMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                contectMouseReleased(evt);
            }
        });
        contect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contectActionPerformed(evt);
            }
        });
        getContentPane().add(contect, new org.netbeans.lib.awtextra.AbsoluteConstraints(789, 305, 136, 32));

        email.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emailMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                emailMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                emailMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                emailMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                emailMouseReleased(evt);
            }
        });
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                emailKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                emailKeyTyped(evt);
            }
        });
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(789, 367, 136, 32));

        aadhar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                aadharMouseExited(evt);
            }
        });
        aadhar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aadharActionPerformed(evt);
            }
        });
        getContentPane().add(aadhar, new org.netbeans.lib.awtextra.AbsoluteConstraints(789, 429, 136, 32));
        getContentPane().add(account, new org.netbeans.lib.awtextra.AbsoluteConstraints(789, 494, 136, 32));

        password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                passwordMouseExited(evt);
            }
        });
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 610, 136, 32));

        register.setBackground(new java.awt.Color(51, 102, 255));
        register.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        register.setForeground(new java.awt.Color(255, 255, 255));
        register.setText("Register");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        getContentPane().add(register, new org.netbeans.lib.awtextra.AbsoluteConstraints(622, 646, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 153, 51));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 440, 70));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Set Password");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 610, 136, 32));

        initialamount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                initialamountMouseExited(evt);
            }
        });
        initialamount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                initialamountActionPerformed(evt);
            }
        });
        getContentPane().add(initialamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 550, 136, 32));

        jButton1.setBackground(new java.awt.Color(51, 102, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        dob.setDateFormatString("dd-MM-yyyy");
        getContentPane().add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(789, 243, 136, 32));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameActionPerformed

    private void contectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contectActionPerformed

    private void aadharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aadharActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aadharActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
adminpage cl=new adminpage();
          
         try{
             Connection con=null;
               con= DriverManager.getConnection("jdbc:mysql://localhost:3306/Banksystem","root","");
     
        String ac_no_prefix="10010001";
        
        int accountno=1;
        PreparedStatement ps_get = con.prepareStatement("select max(cast(accountno as int)) as accountno from customer");
        ResultSet rs_get=ps_get.executeQuery();
        if(rs_get.next())
        {
          accountno=rs_get.getInt("accountno")+1;
        }
        else
        {
            accountno=1;
        }
       
        String formattedaccno=String.format("%03d", accountno);
        
        
        PreparedStatement ps = con.prepareStatement("insert into customer(firstname,lastname,dob,email,contact,aadhar,password,accountno,initialamt,account_prefix,fullaccount) values(?,?,?,?,?,?,?,?,?,?,?)");
        String fn;
        ps.setString(1, fn=fname.getText());
        if(!fn.isEmpty()){
            
        }
        else{
            JOptionPane.showMessageDialog(null, "Please Enter First Name");
        }
        String ln;
        ps.setString(2,ln=lname.getText());
        if(!ln.isEmpty()){
        }
        else{
            JOptionPane.showMessageDialog(null, "Please Enter Last Name");
                    }
        JDateChooser D=dob;
        ps.setString(3,((JTextField)dob.getDateEditor().getUiComponent()).getText());
     String mail;
        ps.setString(4, mail=email.getText());
       
        if(mail.endsWith("@gmail.com")){
            
            
        }
        else{
            JOptionPane.showMessageDialog(null, "Please Enter valid Email id");
                    
        }
        String m;
        ps.setString(5, m=contect.getText());

       if(m.length()==10 && m.matches("^[0-9]+$*")){
           
           
       }
       else{
           JOptionPane.showMessageDialog(null, "invalid mobile number");
       } 
       String aa;
        ps.setString(6, aa=aadhar.getText());
           
      if(aa.length()==12 && aa.matches("^[0-9]+$*")){
          
      }
      else{
          JOptionPane.showMessageDialog(rootPane, "enter valid aadhar card");
      }
      String p;
            ps.setString(7, p=password.getText());
             if(p.length()>=5){
       }
       else{
           JOptionPane.showMessageDialog(null, "enter minimum 5 latters or numbers");
       }
        ps.setString(8, formattedaccno);
        String at;
        ps.setString(9, at=initialamount.getText());
         
       if(at.matches("^[0-9]+$*")){
            
       }
     else{
         JOptionPane.showMessageDialog(null, "please deposit some amount");
     }
        ps.setString(10, ac_no_prefix);
         ps.setString(11, ac_no_prefix+formattedaccno);
         int result;
          if(!fn.isEmpty() && !ln.isEmpty() && mail.endsWith("@gmail.com") && m.length()==10 && m.matches("^[0-9]+$*") && aa.length()==12 && aa.matches("^[0-9]+$*") && p.length()>=5 && at.matches("^[0-9]+$*") ){
        result = ps.executeUpdate();
          }
          else{
              JOptionPane.showMessageDialog(null, "Please Enter Required Feilds");
          }
         PreparedStatement Ps = con.prepareStatement("insert into transcation(account,transactiontype,amount,balance,date,password)values(?,?,?,?,?,?)");
        Ps.setString(1, ac_no_prefix+formattedaccno);
         Ps.setString(2,"initial" );
         Ps.setString(3, initialamount.getText());
          Ps.setString(4, initialamount.getText());
           Ps.setString(5, String.valueOf(new Date()));
         
           Ps.setString(6,password.getText());
            if(!fn.isEmpty() && !ln.isEmpty() && mail.endsWith("@gmail.com") && m.length()==10 && m.matches("^[0-9]+$*") && aa.length()==12 && aa.matches("^[0-9]+$*") && p.length()>=5 && at.matches("^[0-9]+$*") ){
      result = Ps.executeUpdate();
    
JOptionPane.showMessageDialog(null, "Account Create Sucssesfully");
                 cl.setVisible(true);
             setVisible(false);
        
            }
        con.close();
    } catch (SQLException ex) {
              Logger.getLogger(costumerregister.class.getName()).log(Level.SEVERE, null, ex);
        
        
    } 
         
    }//GEN-LAST:event_registerActionPerformed
    
    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // 
    }//GEN-LAST:event_emailActionPerformed

    private void emailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailKeyReleased

    }//GEN-LAST:event_emailKeyReleased

    private void emailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailKeyTyped
      
    }//GEN-LAST:event_emailKeyTyped

    private void emailMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailMouseExited
       
    }//GEN-LAST:event_emailMouseExited

    private void contectMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contectMouseExited
  
               
    }//GEN-LAST:event_contectMouseExited

    private void aadharMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aadharMouseExited
   
    }//GEN-LAST:event_aadharMouseExited

    private void passwordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordMouseExited
      
    }//GEN-LAST:event_passwordMouseExited

    private void initialamountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_initialamountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_initialamountActionPerformed

    private void initialamountMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_initialamountMouseExited
      
    }//GEN-LAST:event_initialamountMouseExited

    private void emailMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailMousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      adminpage ad4=new adminpage();
      ad4.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void contectMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contectMouseReleased
     
    }//GEN-LAST:event_contectMouseReleased

    private void emailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_emailMouseClicked

    private void emailMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_emailMouseEntered

    private void emailMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_emailMouseReleased

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(costumerregister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(costumerregister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(costumerregister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(costumerregister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new costumerregister().setVisible(true);
                
            }
        });
   
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aadhar;
    private javax.swing.JTextField account;
    private javax.swing.JTextField contect;
    private javax.swing.JLabel dgfdh;
    private javax.swing.JLabel dggj;
    private com.toedter.calendar.JDateChooser dob;
    private javax.swing.JLabel dpbe;
    private javax.swing.JLabel eet;
    private javax.swing.JTextField email;
    private javax.swing.JTextField fname;
    private javax.swing.JTextField initialamount;
    private javax.swing.JButton jButton1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lname;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton register;
    private javax.swing.JLabel rthf;
    private javax.swing.JLabel sdlkfdh;
    private javax.swing.JLabel weastflkh;
    private javax.swing.JLabel yutyui;
    // End of variables declaration//GEN-END:variables
}
