/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.banksystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class customerlogin extends javax.swing.JFrame {

    /**
     * Creates new form customerlogin
     */
    public customerlogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customerenteraccount = new javax.swing.JLabel();
        customeraccount = new javax.swing.JTextField();
        customerenterpassword = new javax.swing.JLabel();
        customerpassword = new javax.swing.JPasswordField();
        customerlogin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        customerenteraccount.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        customerenteraccount.setText("Enter Accoutn No");
        customerenteraccount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(customerenteraccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 288, 159, 32));
        getContentPane().add(customeraccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(759, 288, 159, 32));

        customerenterpassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        customerenterpassword.setText("Enter Password");
        customerenterpassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(customerenterpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 426, 159, 32));
        getContentPane().add(customerpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(759, 426, 159, 32));

        customerlogin.setBackground(new java.awt.Color(51, 102, 255));
        customerlogin.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        customerlogin.setForeground(new java.awt.Color(255, 255, 255));
        customerlogin.setText("Login");
        customerlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerloginActionPerformed(evt);
            }
        });
        getContentPane().add(customerlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(631, 538, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Customer Login");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(505, 94, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 102, 51));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 370, 60));

        jButton1.setBackground(new java.awt.Color(51, 102, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void customerloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerloginActionPerformed
      transaction t=new transaction();
      
     try {                                      
            Connection con=null;
            try {
                Class.forName("com.mysql.jdbc.Driver");
                
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Banksystem","root","");
            }
             catch (Exception ex) {
                Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "connection problem: "+ex.getMessage());
                
            }
             PreparedStatement ps = con.prepareStatement("select * from customer where fullaccount=? and password=?");
                           
                          
                            ps.setString(1,customeraccount.getText());
                                     ps.setString(2,customerpassword.getText());
                                     ResultSet rs=ps.executeQuery();
                                       if(rs.next()) { JOptionPane.showMessageDialog(null, "if"); 
                                           
                                            t.setVisible(true);
                                            setVisible(false);
                                       }
                                        else
                                                   {
                                                       JOptionPane.showMessageDialog(null, "Please Enter Required Valid Feilds"); 
                                                   }
     
con.close();
              } catch (SQLException ex) { JOptionPane.showMessageDialog(null,ex.getMessage()); 
                  
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
      
    }//GEN-LAST:event_customerloginActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       home h9=new home();
       h9.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]){
    
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customerlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customerlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customerlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customerlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new customerlogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField customeraccount;
    private javax.swing.JLabel customerenteraccount;
    private javax.swing.JLabel customerenterpassword;
    private javax.swing.JButton customerlogin;
    private javax.swing.JPasswordField customerpassword;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
