/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.banksystem;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import java.util.Scanner;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author DELL
 */
public class depositmoney extends javax.swing.JFrame {

    /**
     * Creates new form depositmoney
     */
    public depositmoney() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        depositaccount = new javax.swing.JLabel();
        account = new javax.swing.JTextField();
        depositamount = new javax.swing.JLabel();
        amount = new javax.swing.JTextField();
        deposit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        depositaccount.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        depositaccount.setText("Account No");
        depositaccount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(depositaccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 306, 136, 33));
        getContentPane().add(account, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 306, 136, 33));

        depositamount.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        depositamount.setText("Enter Amount");
        depositamount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(depositamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 420, 136, 33));
        getContentPane().add(amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 420, 136, 33));

        deposit.setBackground(new java.awt.Color(51, 102, 255));
        deposit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        deposit.setForeground(new java.awt.Color(255, 255, 255));
        deposit.setText("Deposit");
        deposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositActionPerformed(evt);
            }
        });
        getContentPane().add(deposit, new org.netbeans.lib.awtextra.AbsoluteConstraints(624, 521, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Deposit Money");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 141, -1, -1));

        jButton1.setBackground(new java.awt.Color(51, 102, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, -1, 60));

        jPanel2.setBackground(new java.awt.Color(0, 102, 51));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, 370, 70));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        transaction t2=new transaction();
        t2.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void depositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositActionPerformed
     
      
        try {
          Connection con=null;
          try{
              Class.forName("com.mysql.jdbc.Driver");
              con=DriverManager.getConnection("jdbc:mysql://localhost:3306/Banksystem","root","");
             PreparedStatement ps=con.prepareStatement("select * from transcation where account=? order by transactionid desc");
            ps.setString(1, account.getText());
            double pre_balance=0;
            String p1="";
            ResultSet rs=ps.executeQuery();
            if(rs.next())
            {
                pre_balance=rs.getDouble("balance");
                p1=rs.getString("password");
            }
            else{
                JOptionPane.showMessageDialog(null, "Please Enter Required Valid Feilds");
            }
             
              double total_bal=pre_balance+Double.parseDouble(amount.getText());
              
               ps=con.prepareStatement("insert into transcation (transactiontype,amount,balance,date,account,password) values(?,?,?,?,?,?)");
             ps.setString(1, "credit");
             ps.setString(2,amount.getText());
             ps.setString(3, total_bal+"");
              ps.setString(4, String.valueOf(new Date()));
              ps.setString(5, account.getText());
              ps.setString(6, p1);
              int result=ps.executeUpdate();
             
              if(result>0){
              JOptionPane.showMessageDialog(null, "Deposit Successfully");
              transaction t9=new transaction();
              t9.setVisible(true);
                  setVisible(false);
             
             
              }
             
                
              
              
            con.close();
              
          }
         catch(Exception ex){
             ex.printStackTrace();
         }
      }
     catch(Exception ex){
         ex.printStackTrace();
     }
    }//GEN-LAST:event_depositActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(depositmoney.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(depositmoney.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(depositmoney.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(depositmoney.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new depositmoney().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField account;
    private javax.swing.JTextField amount;
    private javax.swing.JButton deposit;
    private javax.swing.JLabel depositaccount;
    private javax.swing.JLabel depositamount;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
