/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.banksystem;

import java.awt.Window;

/**
 *
 * @author DELL
 */
public class transaction extends javax.swing.JFrame {

    /**
     * Creates new form transaction
     */
    public transaction() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        checkbalance = new javax.swing.JButton();
        depositmoney = new javax.swing.JButton();
        withdrawalmoney = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        checkbalance.setBackground(new java.awt.Color(51, 102, 255));
        checkbalance.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        checkbalance.setForeground(new java.awt.Color(255, 255, 255));
        checkbalance.setText("Check Balance");
        checkbalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkbalanceActionPerformed(evt);
            }
        });
        getContentPane().add(checkbalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 261, 247, -1));

        depositmoney.setBackground(new java.awt.Color(51, 102, 255));
        depositmoney.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        depositmoney.setForeground(new java.awt.Color(255, 255, 255));
        depositmoney.setText("Deposit Money");
        depositmoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositmoneyActionPerformed(evt);
            }
        });
        getContentPane().add(depositmoney, new org.netbeans.lib.awtextra.AbsoluteConstraints(759, 261, 260, -1));

        withdrawalmoney.setBackground(new java.awt.Color(51, 102, 255));
        withdrawalmoney.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        withdrawalmoney.setForeground(new java.awt.Color(255, 255, 255));
        withdrawalmoney.setText("Withdrawal Money");
        withdrawalmoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawalmoneyActionPerformed(evt);
            }
        });
        getContentPane().add(withdrawalmoney, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 428, -1, 40));

        exit.setBackground(new java.awt.Color(51, 102, 255));
        exit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 570, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Transactions");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 51, -1, -1));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 102, 51));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, 310, 70));

        jButton1.setBackground(new java.awt.Color(51, 102, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Transaction History");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(759, 428, 260, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void depositmoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositmoneyActionPerformed
        depositmoney dm= new depositmoney();
        dm.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_depositmoneyActionPerformed

    private void checkbalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkbalanceActionPerformed
      checkbalance cb=new checkbalance();
      cb.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_checkbalanceActionPerformed

    private void withdrawalmoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawalmoneyActionPerformed
   withdrawal w=new withdrawal();
   w.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_withdrawalmoneyActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
      customerlogin h=new customerlogin();
       h.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_exitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       transactionhistory tt=new transactionhistory();
       tt.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feeexit     //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new transaction().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkbalance;
    private javax.swing.JButton depositmoney;
    private javax.swing.JButton exit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton withdrawalmoney;
    // End of variables declaration//GEN-END:variables

    void setVisible(String atrue) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
