/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.banksystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class withdrawal extends javax.swing.JFrame {

    /**
     * Creates new form withdrawal
     */
    public withdrawal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        withdrawalaccount = new javax.swing.JLabel();
        account = new javax.swing.JTextField();
        withdrawalamount = new javax.swing.JLabel();
        amount = new javax.swing.JTextField();
        withdrawalpassword = new javax.swing.JLabel();
        password = new javax.swing.JTextField();
        customerwithdrawal = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        withdrawalaccount.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        withdrawalaccount.setText("Account No");
        withdrawalaccount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(withdrawalaccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 224, 132, 30));
        getContentPane().add(account, new org.netbeans.lib.awtextra.AbsoluteConstraints(759, 224, 136, 30));

        withdrawalamount.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        withdrawalamount.setText("Enter Amount");
        withdrawalamount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(withdrawalamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 337, 132, 33));
        getContentPane().add(amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(759, 337, 136, 33));

        withdrawalpassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        withdrawalpassword.setText("Enter Password");
        withdrawalpassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(withdrawalpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 456, -1, 33));
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(759, 456, 136, 33));

        customerwithdrawal.setBackground(new java.awt.Color(51, 102, 255));
        customerwithdrawal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        customerwithdrawal.setForeground(new java.awt.Color(255, 255, 255));
        customerwithdrawal.setText("Withdrawal");
        customerwithdrawal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerwithdrawalActionPerformed(evt);
            }
        });
        getContentPane().add(customerwithdrawal, new org.netbeans.lib.awtextra.AbsoluteConstraints(586, 578, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Withdrawal Money");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 80, -1, -1));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 661, 214, 36));

        jButton1.setBackground(new java.awt.Color(51, 102, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 102, 51));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 460, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     transaction t3=new transaction();
     t3.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void customerwithdrawalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerwithdrawalActionPerformed
         try {
          Connection con=null;
          try{
              Class.forName("com.mysql.jdbc.Driver");
              con=DriverManager.getConnection("jdbc:mysql://localhost:3306/Banksystem","root","");
             PreparedStatement ps=con.prepareStatement("select * from transcation where account=? and password=? order by transactionid desc");
            ps.setString(1, account.getText());
            ps.setString(2, password.getText());
            double pre_balance=0;
           
            ResultSet rs=ps.executeQuery();
            if(rs.next())
            {
                pre_balance=rs.getDouble("balance");
                
            }
            else{
                JOptionPane.showMessageDialog(null, "Please Enter Required Valid Feilds");
            }
             
              double total_bal=pre_balance-Double.parseDouble(amount.getText());
              
               ps=con.prepareStatement("insert into transcation (transactiontype,amount,balance,date,account,password) values(?,?,?,?,?,?)");
             ps.setString(1, "Debit");
             ps.setString(2,amount.getText());
             ps.setString(3,total_bal+"");
              ps.setString(4, String.valueOf(new Date()));
              ps.setString(5, account.getText());
              ps.setString(6, password.getText());
             
              int result=ps.executeUpdate();
             
              if(result>0){
              JOptionPane.showMessageDialog(null, "Withdrawal Successfully");
              transaction t5=new transaction();
              t5.setVisible(true);
                  setVisible(false);
                 
             
             
              }
                            
              
                      
             con.close();
                       }
         catch(Exception ex){
             ex.printStackTrace();
         }
      }
     catch(Exception ex){
         ex.printStackTrace();
     }
                                      

    }//GEN-LAST:event_customerwithdrawalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(withdrawal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(withdrawal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(withdrawal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(withdrawal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new withdrawal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField account;
    private javax.swing.JTextField amount;
    private javax.swing.JButton customerwithdrawal;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField password;
    private javax.swing.JLabel withdrawalaccount;
    private javax.swing.JLabel withdrawalamount;
    private javax.swing.JLabel withdrawalpassword;
    // End of variables declaration//GEN-END:variables
}
